# Regenerate compiled sources after editing a model in inst/odin/:
#
#   Rscript data-raw/generate.R
#
# dust2 currently rejects package names containing dots. The steps below call
# odin2's translator, tolerate only that known error, and finish dust2 source
# generation directly. Generated files are committed and never created by a
# package user.

stopifnot(file.exists("DESCRIPTION"))

# --- 1. odin DSL -> inst/dust/*.cpp -------------------------------------------
# odin2 completes this before dust2 objects to the package name.
translated <- tryCatch(
  {
    odin2::odin_package(".")
    TRUE
  },
  error = function(e) {
    if (!grepl("Package name must not contain", conditionMessage(e))) {
      stop(e)
    }
    message("(skipping dust2's package-name check; see comment above)")
    TRUE
  }
)
stopifnot(translated)

# --- 2. inst/dust/*.cpp -> src/*.cpp + R/dust.R ------------------------------
files <- dir("inst/dust", pattern = "\\.cpp$")
stopifnot(length(files) > 0L)
generated <- lapply(
  file.path("inst/dust", files),
  dust2:::package_generate,
  "insight.cast.odin",
  environment()
)

dir.create("src", showWarnings = FALSE)
for (i in seq_along(files)) {
  writeLines(
    c("// Generated by data-raw/generate.R - do not edit", generated[[i]]$cpp),
    file.path("src", files[[i]])
  )
}
writeLines(
  c(
    "## Generated by data-raw/generate.R - do not edit",
    vapply(generated, "[[", "", "r")
  ),
  "R/dust.R"
)
writeLines(
  c(
    "# -*- makefile -*-",
    "PKG_CXXFLAGS=$(SHLIB_OPENMP_CXXFLAGS)",
    "PKG_LIBS=$(SHLIB_OPENMP_CXXFLAGS)"
  ),
  "src/Makevars"
)

# --- 3. cpp11 registration ----------------------------------------------------
cpp11::cpp_register(".")

message(
  "Generated ", length(files), " system(s): ", paste(files, collapse = ", "),
  "\nNext: devtools::document(); devtools::install()"
)
