// Generated by odin2 (version 0.3.46) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(seir)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(beta, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(sigma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(gamma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(N, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(E0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(phi, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class seir {
public:
  seir() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 5> state;
      } offset;
    } odin;
    real_type beta;
    real_type sigma;
    real_type gamma;
    real_type N;
    real_type E0;
    real_type I0;
    real_type rho;
    real_type phi;
    real_type seed_E;
    real_type seed_I;
  };
  struct internal_state {};
  struct data_type {
    real_type cases;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type beta = dust2::r::read_real(parameters, "beta", 1);
    const real_type sigma = dust2::r::read_real(parameters, "sigma", 1);
    const real_type gamma = dust2::r::read_real(parameters, "gamma", static_cast<real_type>(0.5));
    const real_type N = dust2::r::read_real(parameters, "N", 1e+06);
    const real_type E0 = dust2::r::read_real(parameters, "E0", 10);
    const real_type I0 = dust2::r::read_real(parameters, "I0", 10);
    const real_type rho = dust2::r::read_real(parameters, "rho", 1);
    const real_type phi = dust2::r::read_real(parameters, "phi", 10);
    const real_type seed_E = monty::math::max<real_type>(monty::math::round<real_type>(E0), 0);
    const real_type seed_I = monty::math::max<real_type>(monty::math::round<real_type>(I0), 0);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"E", {}},
      {"I", {}},
      {"R", {}},
      {"incidence", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, beta, sigma, gamma, N, E0, I0, rho, phi, seed_E, seed_I};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto cases = dust2::r::read_real(data, "cases", NA_REAL);
    return data_type{cases};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.beta = dust2::r::read_real(parameters, "beta", shared.beta);
    shared.sigma = dust2::r::read_real(parameters, "sigma", shared.sigma);
    shared.gamma = dust2::r::read_real(parameters, "gamma", shared.gamma);
    shared.N = dust2::r::read_real(parameters, "N", shared.N);
    shared.E0 = dust2::r::read_real(parameters, "E0", shared.E0);
    shared.I0 = dust2::r::read_real(parameters, "I0", shared.I0);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.phi = dust2::r::read_real(parameters, "phi", shared.phi);
    shared.seed_E = monty::math::max<real_type>(monty::math::round<real_type>(shared.E0), 0);
    shared.seed_I = monty::math::max<real_type>(monty::math::round<real_type>(shared.I0), 0);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = shared.N - shared.seed_E - shared.seed_I;
    state[1] = shared.seed_E;
    state[2] = shared.seed_I;
    state[3] = 0;
    state[4] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto E = state[1];
    const auto I = state[2];
    const auto R = state[3];
    const auto incidence = state[4];
    const real_type p_SE = 1 - monty::math::exp<real_type>(-shared.beta * monty::math::max<real_type>(I, 0) / shared.N * dt);
    const real_type p_EI = 1 - monty::math::exp<real_type>(-shared.sigma * dt);
    const real_type p_IR = 1 - monty::math::exp<real_type>(-shared.gamma * dt);
    const real_type n_SE = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(S, 0), p_SE);
    const real_type n_EI = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(E, 0), p_EI);
    const real_type n_IR = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(I, 0), p_IR);
    state_next[0] = S - n_SE;
    state_next[1] = E + n_SE - n_EI;
    state_next[2] = I + n_EI - n_IR;
    state_next[3] = R + n_IR;
    state_next[4] = incidence + n_EI;
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {4}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto incidence = state[4];
    real_type odin_ll = 0;
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.cases, shared.phi, shared.rho * incidence + static_cast<real_type>(9.9999999999999995e-07), true));
    return odin_ll;
  }
};
