// Generated by odin2 (version 0.3.46) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(sir)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(beta, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(gamma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(N, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(phi, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class sir {
public:
  sir() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 4> state;
      } offset;
    } odin;
    real_type beta;
    real_type gamma;
    real_type N;
    real_type I0;
    real_type rho;
    real_type phi;
    real_type seed;
  };
  struct internal_state {};
  struct data_type {
    real_type cases;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type beta = dust2::r::read_real(parameters, "beta", 1);
    const real_type gamma = dust2::r::read_real(parameters, "gamma", static_cast<real_type>(0.5));
    const real_type N = dust2::r::read_real(parameters, "N", 1e+06);
    const real_type I0 = dust2::r::read_real(parameters, "I0", 10);
    const real_type rho = dust2::r::read_real(parameters, "rho", 1);
    const real_type phi = dust2::r::read_real(parameters, "phi", 10);
    const real_type seed = monty::math::max<real_type>(monty::math::round<real_type>(I0), 0);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"I", {}},
      {"R", {}},
      {"incidence", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, beta, gamma, N, I0, rho, phi, seed};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto cases = dust2::r::read_real(data, "cases", NA_REAL);
    return data_type{cases};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.beta = dust2::r::read_real(parameters, "beta", shared.beta);
    shared.gamma = dust2::r::read_real(parameters, "gamma", shared.gamma);
    shared.N = dust2::r::read_real(parameters, "N", shared.N);
    shared.I0 = dust2::r::read_real(parameters, "I0", shared.I0);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.phi = dust2::r::read_real(parameters, "phi", shared.phi);
    shared.seed = monty::math::max<real_type>(monty::math::round<real_type>(shared.I0), 0);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = shared.N - shared.seed;
    state[1] = shared.seed;
    state[2] = 0;
    state[3] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto I = state[1];
    const auto R = state[2];
    const auto incidence = state[3];
    const real_type p_SI = 1 - monty::math::exp<real_type>(-shared.beta * monty::math::max<real_type>(I, 0) / shared.N * dt);
    const real_type p_IR = 1 - monty::math::exp<real_type>(-shared.gamma * dt);
    const real_type n_SI = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(S, 0), p_SI);
    const real_type n_IR = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(I, 0), p_IR);
    state_next[0] = S - n_SI;
    state_next[1] = I + n_SI - n_IR;
    state_next[2] = R + n_IR;
    state_next[3] = incidence + n_SI;
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {3}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto incidence = state[3];
    real_type odin_ll = 0;
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.cases, shared.phi, shared.rho * incidence + static_cast<real_type>(9.9999999999999995e-07), true));
    return odin_ll;
  }
};
