// Generated by data-raw/generate.R - do not edit

// Generated by odin2 (version 0.3.46) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(seir)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(beta, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(sigma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(gamma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(N, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(E0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(phi, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class seir {
public:
  seir() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 5> state;
      } offset;
    } odin;
    real_type beta;
    real_type sigma;
    real_type gamma;
    real_type N;
    real_type E0;
    real_type I0;
    real_type rho;
    real_type phi;
    real_type seed_E;
    real_type seed_I;
  };
  struct internal_state {};
  struct data_type {
    real_type cases;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type beta = dust2::r::read_real(parameters, "beta", 1);
    const real_type sigma = dust2::r::read_real(parameters, "sigma", 1);
    const real_type gamma = dust2::r::read_real(parameters, "gamma", static_cast<real_type>(0.5));
    const real_type N = dust2::r::read_real(parameters, "N", 1e+06);
    const real_type E0 = dust2::r::read_real(parameters, "E0", 10);
    const real_type I0 = dust2::r::read_real(parameters, "I0", 10);
    const real_type rho = dust2::r::read_real(parameters, "rho", 1);
    const real_type phi = dust2::r::read_real(parameters, "phi", 10);
    const real_type seed_E = monty::math::max<real_type>(monty::math::round<real_type>(E0), 0);
    const real_type seed_I = monty::math::max<real_type>(monty::math::round<real_type>(I0), 0);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"E", {}},
      {"I", {}},
      {"R", {}},
      {"incidence", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, beta, sigma, gamma, N, E0, I0, rho, phi, seed_E, seed_I};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto cases = dust2::r::read_real(data, "cases", NA_REAL);
    return data_type{cases};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.beta = dust2::r::read_real(parameters, "beta", shared.beta);
    shared.sigma = dust2::r::read_real(parameters, "sigma", shared.sigma);
    shared.gamma = dust2::r::read_real(parameters, "gamma", shared.gamma);
    shared.N = dust2::r::read_real(parameters, "N", shared.N);
    shared.E0 = dust2::r::read_real(parameters, "E0", shared.E0);
    shared.I0 = dust2::r::read_real(parameters, "I0", shared.I0);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.phi = dust2::r::read_real(parameters, "phi", shared.phi);
    shared.seed_E = monty::math::max<real_type>(monty::math::round<real_type>(shared.E0), 0);
    shared.seed_I = monty::math::max<real_type>(monty::math::round<real_type>(shared.I0), 0);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = shared.N - shared.seed_E - shared.seed_I;
    state[1] = shared.seed_E;
    state[2] = shared.seed_I;
    state[3] = 0;
    state[4] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto E = state[1];
    const auto I = state[2];
    const auto R = state[3];
    const auto incidence = state[4];
    const real_type p_SE = 1 - monty::math::exp<real_type>(-shared.beta * monty::math::max<real_type>(I, 0) / shared.N * dt);
    const real_type p_EI = 1 - monty::math::exp<real_type>(-shared.sigma * dt);
    const real_type p_IR = 1 - monty::math::exp<real_type>(-shared.gamma * dt);
    const real_type n_SE = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(S, 0), p_SE);
    const real_type n_EI = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(E, 0), p_EI);
    const real_type n_IR = monty::random::binomial<real_type>(rng_state, monty::math::max<real_type>(I, 0), p_IR);
    state_next[0] = S - n_SE;
    state_next[1] = E + n_SE - n_EI;
    state_next[2] = I + n_EI - n_IR;
    state_next[3] = R + n_IR;
    state_next[4] = incidence + n_EI;
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {4}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto incidence = state[4];
    real_type odin_ll = 0;
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.cases, shared.phi, shared.rho * incidence + static_cast<real_type>(9.9999999999999995e-07), true));
    return odin_ll;
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>
#include <dust2/r/discrete/filter.hpp>
#include <dust2/r/discrete/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_system_seir_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<seir>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_seir_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<seir>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_seir_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<seir>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_seir_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<seir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_seir_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<seir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_seir_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<seir>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_seir_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<seir>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_seir_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<seir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_seir_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<seir>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_seir_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<seir>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_seir_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<seir>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_seir_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<seir>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_seir_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_unfilter_alloc<seir>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_filter_seir_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed) {
  return dust2::r::dust2_discrete_filter_alloc<seir>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed);
}
[[cpp11::register]]
SEXP dust2_system_seir_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_compare_data<dust2::dust_discrete<seir>>(ptr, r_data, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_seir_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_unfilter_update_pars<dust2::dust_discrete<seir>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_unfilter_seir_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_run<dust2::dust_discrete<seir>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_seir_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_trajectories<dust2::dust_discrete<seir>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_seir_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_snapshots<dust2::dust_discrete<seir>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_seir_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_state<dust2::dust_discrete<seir>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_seir_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_filter_update_pars<dust2::dust_discrete<seir>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_filter_seir_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_run<dust2::dust_discrete<seir>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_seir_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_trajectories<dust2::dust_discrete<seir>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_seir_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_snapshots<dust2::dust_discrete<seir>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_seir_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_state<dust2::dust_discrete<seir>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_seir_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_filter_rng_state<dust2::dust_discrete<seir>>(ptr);
}

[[cpp11::register]]
SEXP dust2_filter_seir_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_filter_set_rng_state<dust2::dust_discrete<seir>>(ptr, r_rng_state);
}
