# Generated by cpp11: do not edit by hand

dust2_system_seir_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_insight_cast_odin_dust2_system_seir_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_seir_run_to_time <- function(ptr, r_time) {
  .Call(`_insight_cast_odin_dust2_system_seir_run_to_time`, ptr, r_time)
}

dust2_system_seir_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_system_seir_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_seir_time <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_system_seir_time`, ptr)
}

dust2_system_seir_set_state_initial <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_system_seir_set_state_initial`, ptr)
}

dust2_system_seir_set_state <- function(ptr, r_state) {
  .Call(`_insight_cast_odin_dust2_system_seir_set_state`, ptr, r_state)
}

dust2_system_seir_reorder <- function(ptr, r_index) {
  .Call(`_insight_cast_odin_dust2_system_seir_reorder`, ptr, r_index)
}

dust2_system_seir_rng_state <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_system_seir_rng_state`, ptr)
}

dust2_system_seir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_insight_cast_odin_dust2_system_seir_set_rng_state`, ptr, r_rng_state)
}

dust2_system_seir_set_time <- function(ptr, r_time) {
  .Call(`_insight_cast_odin_dust2_system_seir_set_time`, ptr, r_time)
}

dust2_system_seir_update_pars <- function(ptr, pars) {
  .Call(`_insight_cast_odin_dust2_system_seir_update_pars`, ptr, pars)
}

dust2_system_seir_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_system_seir_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_seir_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_insight_cast_odin_dust2_unfilter_seir_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_seir_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_insight_cast_odin_dust2_filter_seir_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_seir_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_system_seir_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_seir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_insight_cast_odin_dust2_unfilter_seir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_seir_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_seir_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_seir_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_seir_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_seir_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_seir_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_seir_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_seir_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_seir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_insight_cast_odin_dust2_filter_seir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_seir_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_seir_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_seir_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_seir_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_seir_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_seir_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_seir_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_seir_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_seir_rng_state <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_filter_seir_rng_state`, ptr)
}

dust2_filter_seir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_insight_cast_odin_dust2_filter_seir_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sir_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_insight_cast_odin_dust2_system_sir_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sir_run_to_time <- function(ptr, r_time) {
  .Call(`_insight_cast_odin_dust2_system_sir_run_to_time`, ptr, r_time)
}

dust2_system_sir_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_system_sir_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sir_time <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_system_sir_time`, ptr)
}

dust2_system_sir_set_state_initial <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_system_sir_set_state_initial`, ptr)
}

dust2_system_sir_set_state <- function(ptr, r_state) {
  .Call(`_insight_cast_odin_dust2_system_sir_set_state`, ptr, r_state)
}

dust2_system_sir_reorder <- function(ptr, r_index) {
  .Call(`_insight_cast_odin_dust2_system_sir_reorder`, ptr, r_index)
}

dust2_system_sir_rng_state <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_system_sir_rng_state`, ptr)
}

dust2_system_sir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_insight_cast_odin_dust2_system_sir_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sir_set_time <- function(ptr, r_time) {
  .Call(`_insight_cast_odin_dust2_system_sir_set_time`, ptr, r_time)
}

dust2_system_sir_update_pars <- function(ptr, pars) {
  .Call(`_insight_cast_odin_dust2_system_sir_update_pars`, ptr, pars)
}

dust2_system_sir_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_system_sir_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_insight_cast_odin_dust2_unfilter_sir_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_sir_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_insight_cast_odin_dust2_filter_sir_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_sir_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_system_sir_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_insight_cast_odin_dust2_unfilter_sir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_sir_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_sir_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_sir_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_sir_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_sir_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_unfilter_sir_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_insight_cast_odin_dust2_filter_sir_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_sir_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_sir_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_sir_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_sir_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_insight_cast_odin_dust2_filter_sir_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_sir_rng_state <- function(ptr) {
  .Call(`_insight_cast_odin_dust2_filter_sir_rng_state`, ptr)
}

dust2_filter_sir_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_insight_cast_odin_dust2_filter_sir_set_rng_state`, ptr, r_rng_state)
}
