## Generated by data-raw/generate.R - do not edit
seir <- structure(
  function() get("seir"),
  class = "dust_system_generator",
  name = "seir",
  package = "insight.cast.odin",
  path = NULL,
  parameters = data.frame(
    name = c("beta", "sigma", "gamma", "N", "E0", "I0", "rho", "phi"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
sir <- structure(
  function() get("sir"),
  class = "dust_system_generator",
  name = "sir",
  package = "insight.cast.odin",
  path = NULL,
  parameters = data.frame(
    name = c("beta", "gamma", "N", "I0", "rho", "phi"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
